# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the 'frontend' directory from your host to /app in the container
COPY ./web-app .

# Install necessary Python packages
RUN pip3 install Flask pyzmq

# Run 'app.py' when the container launches
CMD ["python3", "./app.py"]