{{- range .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .app }}
  template:
    metadata:
      labels:
        app: {{ .app }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: {{ .containerName }}
        image: "{{ .imageRegistry }}/{{ .imageName }}:{{ .imageTag }}"
        imagePullPolicy: Always
        ports:
        {{- range .ports }}
        - containerPort: {{ .containerPort }}
        {{- end }}
        env:
        {{- range .env }}
        - name: {{ .name }}
          {{- if .configMapName }}
          valueFrom:
            configMapKeyRef:
              name: {{ .configMapName }}
              key: {{ .key }}
          {{- else }}
          value: {{ .value }}
          {{- end }}
        {{- end }}
---
{{- end }}