configMaps:
  - name: frontend-config-map
    data:
      streaming_server_ip: ""
      streaming_parameters_controller_ip: "receiver-encoder-publisher-service"
      ros_bridge_server_ip: ""
      bitrate_port: "5556"
      speed_preset_port: "5557"
      resolution_port: "5558"
  - name: receiver-encoder-publisher-config-map
    data:
      port: "5555"
      width: "1920"
      height: "1080"
      bit_rate: "4000"
      speed_preset: "ultrafast"
      server: "mediamtx-service"
      bit_rate_port: "5556"
      speed_preset_port: "5557"
      resolution_port: "5558"
  - name: object-detector-config-map
    data:
      port: "5559"
      yolo_model: "yolov8n.pt"
  - name: sampler-sender-config-map
    data:
      port: "5554"
      framerate: "1/1"
      destination_ip: "object-detector-service"
      destination_port: "5559"
      framerate_port: "5560"