apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx # Label to target Pods with a Service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
