services:
  - name: object-detector-service
    app: object-detector
    type: LoadBalancer
    ports:
      - name: get-frames-from-sampler-sender
        protocol: UDP
        port: 5559
        targetPort: 5559